"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const FileSearch_1 = require("./FileSearch");
const params = new FileSearch_1.SearchParams();
params.extension = "xml";
params.minSize = 2;
params.maxSize = 100;
const xmlFile = new FileSearch_1.FileEntry();
xmlFile.setContent(new Blob(["<test>abcabc<test/>"]));
xmlFile.setName("aaa.xml");
const textFile = new FileSearch_1.FileEntry();
textFile.setContent(new Blob(["this is text"]));
textFile.setName("bbb.txt");
const jsonFile = new FileSearch_1.FileEntry();
jsonFile.setContent(new Blob(["{a:'line one'}"]));
jsonFile.setName("ccc.json");
const dir1 = new FileSearch_1.FolderEntry();
dir1.addEntry(textFile);
dir1.addEntry(xmlFile);
const dir0 = new FileSearch_1.FolderEntry();
dir0.addEntry(jsonFile);
dir0.addEntry(dir1);
const searcher = new FileSearch_1.FileSearch();
console.log(searcher.search(dir0, params));
//# sourceMappingURL=test.js.map